# Generated by Django 4.1.1 on 2023-10-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_articulos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'curso'},
        ),
    ]
